#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 18 15:07:44 UTC 2026
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim lab_02_tb_alu_behav -key {Behavioral:sim_1:Functional:lab_02_tb_alu} -tclbatch lab_02_tb_alu.tcl -view /home/pin_34_11/mpsis_semester6/lab_01_tb_fulladder_behav.wcfg -log simulate.log"
xsim lab_02_tb_alu_behav -key {Behavioral:sim_1:Functional:lab_02_tb_alu} -tclbatch lab_02_tb_alu.tcl -view /home/pin_34_11/mpsis_semester6/lab_01_tb_fulladder_behav.wcfg -log simulate.log

