#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 16 18:35:46 UTC 2026
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim lab_01_tb_fulladder32_behav -key {Behavioral:sim_1:Functional:lab_01_tb_fulladder32} -tclbatch lab_01_tb_fulladder32.tcl -view /home/pin_34_11/mpsis_semester6/lab_01_tb_fulladder_behav.wcfg -log simulate.log"
xsim lab_01_tb_fulladder32_behav -key {Behavioral:sim_1:Functional:lab_01_tb_fulladder32} -tclbatch lab_01_tb_fulladder32.tcl -view /home/pin_34_11/mpsis_semester6/lab_01_tb_fulladder_behav.wcfg -log simulate.log

